spring:
  application:
    name: osm-organization-service
  datasource:
    url: jdbc:postgresql://org-service-db:5432/org_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 600000
      connection-test-query: SELECT 1
  sql:
    init:
      platform: postgres
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

management:
  endpoints:
    web:
      exposure:
        include: '*'
    access:
      default: unrestricted
