INSERT INTO contributor (type, name)
VALUES ('Collaborator', 'Alice'),
       ('Contributor', 'Bob'),
       ('Owner', 'Charlie'),
       ('Member', 'David'),
       ('Outside Collaborator', 'Eve'),
       ('Bot', 'Bot1'),
       ('Collaborator', 'Frank'),
       ('Contributor', 'Grace'),
       ('Owner', 'Heidi'),
       ('Member', 'Ivan'),
       ('Outside Collaborator', 'Judy'),
       ('Bot', 'Bot2'),
       ('Collaborator', 'Mallory'),
       ('Contributor', 'Niaj'),
       ('Owner', 'Olivia'),
       ('Member', 'Peggy'),
       ('Outside Collaborator', 'Sybil'),
       ('Bot', 'Bot3'),
       ('Collaborator', 'Trent'),
       ('Contributor', 'Victor');